- name: Pull docker image and run docker 
  hosts: local
  become: no
  tasks: 

    - name: Pull Docker Image from registry
      docker_image:
        name: "meenalj21/scientific-calculator"
        tag: latest
        source: pull

    - name: Run Docker Container
      docker_container:
        name: "scientific-calc"
        image: "meenalj21/scientific-calculator:latest"
        state: started
        restart_policy: always
        published_ports:
          - "5000:8000"
    
  rescue:
    - name: Remove Failed Containers (if exists)
      command: docker rm -f scientific-calc
      ignore_errors: yes

    - name: Log Failure Message
      debug: 
        msg: "Docker deployment failed! Check logs!"
          
