- name: Pull docker image and run docker 
  hosts: local
  become: no
  vars:
    docker_registry: "{{ lookup('env', 'REGISTRY') }}"
    image_name: "{{ lookup('env', 'IMAGE_NAME') }}"
    container_name: "{{ lookup('env', 'CONTAINER_NAME') }}"
  tasks: 

    - name: Pull Docker Image from registry
      docker_image:
        name: "{{ docker_registry }}/{{ image_name }}"
        tag: latest
        source: pull

    - name: Run Docker Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_registry }}/{{ image_name }}:latest"
        state: started
        restart_policy: always
        published_ports:
          - "5000:8000"
          
